import type { NextPage } from 'next';
import Head from 'next/head';
import ProducSearchItem from '../components/productSearchItem';
import HomePage from '../components/HomePage';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Website Name</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomePage />
    </>
  );
};

export default Home;
