
name: Build and Deploy to Cloud Run

defaults:
  run:
    working-directory: public_front_end

on:
  push:
    branches:
    - main
    paths:
      - public_front_end/**

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: asia-southeast1
  SERVICE_NAME: tofa_circle_public_fe

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check files
      run: ls -a
    # - name: Change directory
    #   run: cd public_front_end

    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.RUN_SA_KEY }}'

    # Setup gcloud CLI
    - name: Setup GCloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.RUN_PROJECT }}
        # version: '290.0.1'
        # service_account_key: ${{ secrets.RUN_SA_KEY }}

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
          --timeout=30m
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated